In [100]:
#Libraries importation
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')

In [101]:
#Reading data
data = pd.read_excel('Retail-Supply-Chain-Sales-Dataset.xlsx')

DATA EXPLORING

In [102]:
data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Retail Sales People,Product ID,Category,Sub-Category,Product Name,Returned,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-08-11,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Cassandra Brandow,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,Not,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-08-11,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Cassandra Brandow,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",Not,731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-12-06,2016-12-06,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Anna Andreadi,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,Not,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-11-10,2015-11-10,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Cassandra Brandow,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,Not,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-11-10,2015-11-10,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Cassandra Brandow,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,Not,22.3680,2,0.20,2.5164

In [103]:
data.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Retail Sales People', 'Product ID',
       'Category', 'Sub-Category', 'Product Name', 'Returned', 'Sales',
       'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [104]:
data = data.drop(['Row ID', 'Order ID', 'Customer ID', 'Customer Name', 'Postal Code', 'Product ID'], axis=1)

In [105]:
data.head()

,Order Date,Ship Date,Ship Mode,Segment,Country,City,State,Region,Retail Sales People,Category,Sub-Category,Product Name,Returned,Sales,Quantity,Discount,Profit
0,2016-08-11,2016-11-11,Second Class,Consumer,United States,Henderson,Kentucky,South,Cassandra Brandow,Furniture,Bookcases,Bush Somerset Collection Bookcase,Not,261.9600,2,0.00,41.9136
1,2016-08-11,2016-11-11,Second Class,Consumer,United States,Henderson,Kentucky,South,Cassandra Brandow,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",Not,731.9400,3,0.00,219.5820
2,2016-12-06,2016-12-06,Second Class,Corporate,United States,Los Angeles,California,West,Anna Andreadi,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,Not,14.6200,2,0.00,6.8714
3,2015-11-10,2015-11-10,Standard Class,Consumer,United States,Fort Lauderdale,Florida,South,Cassandra Brandow,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,Not,957.5775,5,0.45,-383.0310
4,2015-11-10,2015-11-10,Standard Class,Consumer,United States,Fort Lauderdale,Florida,South,Cassandra Brandow,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,Not,22.3680,2,0.20,2.5164

In [106]:
data.isna().sum()

Order Date             0
Ship Date              0
Ship Mode              0
Segment                0
Country                0
City                   0
State                  0
Region                 0
Retail Sales People    0
Category               0
Sub-Category           0
Product Name           0
Returned               0
Sales                  0
Quantity               0
Discount               0
Profit                 0
dtype: int64

In [107]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Order Date           9994 non-null   datetime64[ns]
 1   Ship Date            9994 non-null   datetime64[ns]
 2   Ship Mode            9994 non-null   object
 3   Segment              9994 non-null   object
 4   Country              9994 non-null   object
 5   City                 9994 non-null   object
 6   State                9994 non-null   object
 7   Region               9994 non-null   object
 8   Retail Sales People  9994 non-null   object
 9   Category             9994 non-null   object
 10  Sub-Category         9994 non-null   object
 11  Product Name         9994 non-null   object
 12  Returned             9994 non-null   object
 13  Sales                9994 non-null   float64
 14  Quantity             9994 non-null   int64
 15  Discount             9994 non-null   float64
 16  Profit               9994 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(1), object(11)
memory usage: 1.3+ MB

In [108]:
data.describe().T

,count,mean,min,25%,50%,75%,max,std
Order Date,9994,2016-04-11 07:17:44.078447104,2014-01-02 00:00:00,2015-05-01 00:00:00,2016-05-30 00:00:00,2017-04-09 00:00:00,2017-12-30 00:00:00,NaN
Ship Date,9994,2016-05-15 21:54:47.332399360,2014-01-15 00:00:00,2015-06-20 00:00:00,2016-07-21 00:00:00,2017-06-02 00:00:00,2018-05-01 00:00:00,NaN
Sales,9994.0,229.858001,0.444,17.28,54.49,209.94,22638.48,623.245101
Quantity,9994.0,3.789574,1.0,2.0,3.0,5.0,14.0,2.22511
Discount,9994.0,0.156203,0.0,0.0,0.2,0.2,0.8,0.206452
Profit,9994.0,28.656896,-6599.978,1.72875,8.6665,29.364,8399.976,234.260108

In [109]:
data.describe(include=object).T

                    count unique              top  freq
Ship Mode            9994      4   Standard Class  5968
Segment              9994      3         Consumer  5191
Country              9994      1    United States  9994
City                 9994    531    New York City   915
State                9994     49       California  2001
Region               9994      4             West  3203
Retail Sales People  9994      4    Anna Andreadi  3203
Category             9994      3  Office Supplies  6026
Sub-Category         9994     17          Binders  1523
Product Name         9994   1850  Staple envelope    48
Returned             9994      2              Not  9194

DATA ANALYSIS

In [110]:
#Total revenue
total_revenue = data['Sales'].sum()

print(f"Total revenue is : {total_revenue}$")

Total revenue is : 2297200.8603000003$

Products analysis

In [111]:
#The categories with the most benefit
most_revenue_cat = data.groupby('Category')['Sales'].sum().reset_index()

most_revenue_cat = most_revenue_cat.sort_values(by='Sales', ascending=False)

print(most_revenue_cat)

          Category        Sales
2       Technology  836154.0330
0        Furniture  741999.7953
1  Office Supplies  719047.0320

In [112]:
fig1 = px.pie(data_frame=most_revenue_cat, names='Category', values='Sales')
fig1.update_layout(title="Revenue distribution by categoy")
fig1.show()

In [113]:
# Categories sales
most_sal_cat = data.groupby('Category')['Quantity'].sum().reset_index()

most_sal_cat = most_sal_cat.sort_values(by='Quantity', ascending=False)

print(most_sal_cat)

          Category  Quantity
1  Office Supplies     22906
0        Furniture      8028
2       Technology      6939

In [114]:
fig1 = px.pie(data_frame=most_sal_cat, names='Category', values='Quantity')
fig1.update_layout(title="Categories sales")
fig1.show()

In [115]:
# Top 10 subcategories with the most benefit
most_revenu_subcat = data.groupby('Sub-Category')['Sales'].sum().reset_index()

most_revenu_subcat = most_revenu_subcat.sort_values(by='Sales', ascending=False)

most_revenu_subcat = most_revenu_subcat.head(10)

print(most_revenu_subcat)

   Sub-Category        Sales
13       Phones  330007.0540
5        Chairs  328449.1030
14      Storage  223843.6080
16       Tables  206965.5320
3       Binders  203412.7330
11     Machines  189238.6310
0   Accessories  167380.3180
6       Copiers  149528.0300
4     Bookcases  114879.9963
1    Appliances  107532.1610

In [116]:
fig2 = px.bar(data_frame=most_revenu_subcat, x='Sub-Category', y='Sales')
fig2.update_layout(title="Top 10 subcategories revenue")
fig2.show()

In [117]:
# Top 10 sales subcategories
most_sales_subcat = data.groupby('Sub-Category')['Quantity'].sum().reset_index()

most_sales_subcat = most_sales_subcat.sort_values(by='Quantity', ascending=False)

most_sales_subcat = most_sales_subcat.head(10)

print(most_sales_subcat)

   Sub-Category  Quantity
3       Binders      5974
12        Paper      5178
9   Furnishings      3563
13       Phones      3289
14      Storage      3158
2           Art      3000
0   Accessories      2976
5        Chairs      2356
1    Appliances      1729
10       Labels      1400

In [118]:
fig2 = px.bar(data_frame=most_sales_subcat, x='Sub-Category', y='Quantity')
fig2.update_layout(title="Top 10 sales subcategories")
fig2.show()

Geographic analysis

In [119]:
#By region
reg_sales = data.groupby('Region')['Sales'].sum().reset_index()

reg_sales = reg_sales.sort_values(by='Sales', ascending=False)

print(reg_sales)

    Region        Sales
3     West  725457.8245
1     East  678781.2400
0  Central  501239.8908
2    South  391721.9050

In [120]:
fig3 = px.pie(data_frame=reg_sales, names='Region', values='Sales')
fig3.update_layout(title="Revenue distribution By Region")
fig3.show()

In [121]:
# By state
state_sales = data.groupby('State')['Sales'].sum().reset_index()

state_sales = state_sales.sort_values(by='Sales', ascending=False)

state_sales = state_sales.head(10)

print(state_sales)

           State        Sales
3     California  457687.6315
30      New York  310876.2710
41         Texas  170188.0458
45    Washington  138641.2700
36  Pennsylvania  116511.9140
8        Florida   89473.7080
11      Illinois   80166.1010
33          Ohio   78258.1360
20      Michigan   76269.6140
44      Virginia   70636.7200

In [122]:
fig4 = px.bar(data_frame=state_sales, x='State', y='Sales')
fig4.update_layout(title="Top 10 states revenue")
fig4.show()

Segment analysis

In [123]:
# Revenue by segment
seg_sales = data.groupby('Segment')['Sales'].sum().reset_index()

seg_sales = seg_sales.sort_values(by='Sales', ascending=False)

print(seg_sales)

       Segment         Sales
0     Consumer  1.161401e+06
1    Corporate  7.061464e+05
2  Home Office  4.296531e+05

In [124]:
fig5 = px.pie(data_frame=seg_sales, names='Segment', values='Sales', color='Segment',
              color_discrete_map={'Home Office':'lightcyan',
                                 'Corporate':'cyan',
                                 'Consumer':'royalblue',
                                 }, 
              title="Revenue distribution by segment",)
fig5.show()

In [125]:
data.columns

Index(['Order Date', 'Ship Date', 'Ship Mode', 'Segment', 'Country', 'City',
       'State', 'Region', 'Retail Sales People', 'Category', 'Sub-Category',
       'Product Name', 'Returned', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [126]:
# Converting "Date" colums to the right format

data['Order Date'] = pd.to_datetime(data['Order Date'], format="%Y-%m-%d")

data['Ship Date'] = pd.to_datetime(data['Ship Date'], format="%Y-%m-%d")

In [127]:
data['Month'] = data['Ship Date'].dt.month

data['Month'] = data['Month']

# Calculation of the monthly sales trend
monthly_sales = data.groupby('Month')['Sales'].sum().reset_index()

In [128]:
fig6 = px.line(data_frame=monthly_sales, x='Month', y='Sales', markers=True, title='Monthly sales')
fig6.show()

In [129]:
# Add column year-mounth
data['Year-Month'] = data['Ship Date'].dt.to_period('M')


data['Year-Month'] = data['Year-Month'].astype(str)

# Sales by mounth/year
monthly_sales_by_year = data.groupby('Year-Month')['Sales'].sum().reset_index()

In [130]:
fig6 = px.line(data_frame=monthly_sales_by_year, x='Year-Month', y='Sales')
fig6.show()

Returns analysis

In [133]:
returns = data[data['Returned'] == 'Yes']

returns_by_category = returns.groupby('Category')['Sales'].sum().reset_index()

In [134]:
returns_by_category

          Category       Sales
0        Furniture  59219.1749
1  Office Supplies  48576.9290
2       Technology  72708.1740

In [135]:
fig8 = px.bar(data_frame=returns_by_category, x='Category', y='Sales',
              title='Returned sales by categories')
fig8.show()

In [136]:
returns_by_subcategory = returns.groupby('Sub-Category')['Sales'].sum().reset_index()

returns_by_subcategory = returns_by_subcategory.sort_values(by='Sales', ascending=False)

In [137]:
fig8 = px.bar(data_frame=returns_by_subcategory, x='Sub-Category', y='Sales', color='Sales',
              text_auto='.2s',
              title='Returned sales by subcategories')
fig8.show()

In [138]:
# Analysis of sales with and without discounts
pos_discount = data[data['Discount'] > 0]

sales_with_discount = pos_discount.groupby('Discount')['Sales'].sum().reset_index()

In [139]:
# Discount visualisation
fig8 =  px.line(data_frame=sales_with_discount, x='Discount', y='Sales', text='Discount', 
                title="Sales distribution by discounts")
fig8.update_traces(textposition="bottom right", line = dict(color='blue'))
fig8.show()